export const CONFIG = Object.freeze({
  // Screen
  SCREEN_WIDTH: 960,
  SCREEN_HEIGHT: 540,

  // Player
  PLAYER_WIDTH: 32,
  PLAYER_HEIGHT: 48,
  PLAYER_COLOR: 0x00cc44,
  PLAYER_SPEED: 4.0,
  JUMP_FORCE: -12.0,
  GRAVITY: 0.6,
  MAX_FALL_SPEED: 15.0,

  // Policeman
  POLICEMAN_WIDTH: 32,
  POLICEMAN_HEIGHT: 48,
  POLICEMAN_COLOR: 0xcc0000,
  POLICEMAN_TRAIL_DELAY: 40,
  POLICEMAN_SPEED_MULT: 1.0,
  BREADCRUMB_RECORD_INTERVAL: 3,
  CATCH_DISTANCE: 24,

  // Platforms
  PLATFORM_COLOR: 0x8b4513,
  PLATFORM_MIN_WIDTH: 80,
  PLATFORM_MAX_WIDTH: 200,
  PLATFORM_HEIGHT: 20,
  GROUND_Y: 480,
  GROUND_HEIGHT: 40,

  // Level generation
  WORLD_WIDTH: 8000,
  WORLD_HEIGHT: 700,
  PLATFORM_COUNT: 40,
  METAL_COUNT: 10,

  // Metal pieces
  METAL_WIDTH: 16,
  METAL_HEIGHT: 16,
  METAL_COLOR: 0xffd700,

  // Camera
  CAMERA_ZOOM: 2,
  CAMERA_OFFSET_X: 0.3,
  CAMERA_LERP: 0.1,
});
